/* values for table MED_JOURNAL */
/*INSERT INTO MED_JOURNAL (JOURNAL_ID,JOURNAL_CREATE_DATE,JOURNAL_LAST_UPDATED,JOURNAL_NAME,JOURNAL_USER_ID) VALUES (1,'01.01.2019','2019-01-01','FirstMedicalJournal',1);*/

/* values for table MED_JOURNAL_ENTRY */ 

/*INSERT INTO MED_JOURNAL_ENTRY (JOURNAL_ENTRY_ID,JOURNAL_ENTRY_DATE,JOURNAL_ENTRY_CREATE_DATE,JOURNAL_ENTRY_LAST_UPDATED,JOURNAL_ENTRY_PULSE,JOURNAL_ENTRY_HEIGHT,JOURNAL_ENTRY_WEIGHT,JOURNAL_ENTRY_BMI,JOURNAL_ENTRY_IS_SICK,JOURNAL_ID,BLOOD_PRESSURE_SYS,BLOOD_PRESSURE_DIA,JOURNAL_ENTRY_NOTE) VALUES (1,'2019-01-01','2019-01-01','2019-01-01',80,185,80,25,false,1,130,80,'Testeintrag für Tagebuch')*/

