/* schema for table MED_JOURNAL */
CREATE TABLE MED_JOURNAL (
	JOURNAL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	JOURNAL_CREATE_DATE date NOT NULL,
	JOURNAL_LAST_UPDATED date NOT NULL,
	JOURNAL_NAME varchar(100) NOT NULL,
	JOURNAL_USER_ID BIGINT 

);


/* schema for table MED_JOURNAL_ENTRY */
CREATE TABLE MED_JOURNAL_ENTRY (
	JOURNAL_ENTRY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	JOURNAL_ENTRY_DATE date NOT NULL,
	JOURNAL_ENTRY_CREATE_DATE date NOT NULL,
	JOURNAL_ENTRY_LAST_UPDATED date NOT NULL,
	JOURNAL_ENTRY_PULSE SMALLINT ,
	JOURNAL_ENTRY_HEIGHT SMALLINT ,
	JOURNAL_ENTRY_WEIGHT SMALLINT ,
	JOURNAL_ENTRY_BMI SMALLINT ,
	JOURNAL_ENTRY_IS_SICK BOOLEAN ,
	JOURNAL_ID BIGINT ,
	BLOOD_PRESSURE_SYS SMALLINT ,
	BLOOD_PRESSURE_DIA SMALLINT ,
	JOURNAL_ENTRY_NOTE varchar(100),
	FOREIGN KEY (JOURNAL_ID) REFERENCES MED_JOURNAL(JOURNAL_ID)
);
